RUNNING: "python -m dask_cuda.cli.dask_cuda_worker --rmm-pool-size=28G
             --local-directory=/tmp/
             --scheduler-file=/root/cugraph/python/cugraph-pyg/cugraph_pyg/examples/scheduler.json
             --memory-limit=auto
             --device-memory-limit=auto
            "
2023-04-04 04:43:01,774 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.104.11:36467'
2023-04-04 04:43:01,776 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.104.11:44293'
2023-04-04 04:43:02,899 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-04-04 04:43:02,899 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-04-04 04:43:02,945 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-04-04 04:43:02,945 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-04-04 04:43:03,141 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-04-04 04:43:03,204 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-04-04 04:43:04,489 - distributed.worker - INFO -       Start worker at:  tcp://10.120.104.11:46393
2023-04-04 04:43:04,489 - distributed.worker - INFO -          Listening to:  tcp://10.120.104.11:46393
2023-04-04 04:43:04,489 - distributed.worker - INFO -          dashboard at:        10.120.104.11:46349
2023-04-04 04:43:04,489 - distributed.worker - INFO - Waiting to connect to:   tcp://10.120.104.11:8786
2023-04-04 04:43:04,489 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 04:43:04,489 - distributed.worker - INFO -               Threads:                          1
2023-04-04 04:43:04,489 - distributed.worker - INFO -                Memory:                 755.28 GiB
2023-04-04 04:43:04,489 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-79jsphc0
2023-04-04 04:43:04,490 - distributed.worker - INFO - Starting Worker plugin RMMSetup-baa5d822-ae6d-4291-815e-b14e9ef2205a
2023-04-04 04:43:04,509 - distributed.worker - INFO -       Start worker at:  tcp://10.120.104.11:44455
2023-04-04 04:43:04,509 - distributed.worker - INFO -          Listening to:  tcp://10.120.104.11:44455
2023-04-04 04:43:04,509 - distributed.worker - INFO -          dashboard at:        10.120.104.11:38095
2023-04-04 04:43:04,509 - distributed.worker - INFO - Waiting to connect to:   tcp://10.120.104.11:8786
2023-04-04 04:43:04,509 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 04:43:04,509 - distributed.worker - INFO -               Threads:                          1
2023-04-04 04:43:04,509 - distributed.worker - INFO -                Memory:                 755.28 GiB
2023-04-04 04:43:04,509 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-pdtgqye9
2023-04-04 04:43:04,510 - distributed.worker - INFO - Starting Worker plugin PreImport-7e397dcb-8471-4ec8-9431-18009392f9de
2023-04-04 04:43:04,510 - distributed.worker - INFO - Starting Worker plugin RMMSetup-db7c9cda-920a-4892-ae07-beaef5c691d9
2023-04-04 04:43:04,629 - distributed.worker - INFO - Starting Worker plugin PreImport-f722cf45-5322-4d0d-9f3f-a8d920d5e3b2
2023-04-04 04:43:04,629 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-f6a4ae1f-d6f9-44c9-bbdc-973d4023930e
2023-04-04 04:43:04,633 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 04:43:04,645 - distributed.worker - INFO -         Registered to:   tcp://10.120.104.11:8786
2023-04-04 04:43:04,646 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 04:43:04,648 - distributed.core - INFO - Starting established connection to tcp://10.120.104.11:8786
2023-04-04 04:43:04,671 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-e0269533-9944-4d83-a87e-4ca55a6aeea9
2023-04-04 04:43:04,672 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 04:43:04,680 - distributed.worker - INFO -         Registered to:   tcp://10.120.104.11:8786
2023-04-04 04:43:04,680 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 04:43:04,682 - distributed.core - INFO - Starting established connection to tcp://10.120.104.11:8786
2023-04-04 04:43:27,906 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 04:43:27,906 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 04:43:28,722 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 04:43:28,722 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 04:43:29,388 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 04:43:29,406 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 04:43:29,412 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 04:43:29,412 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 04:43:37,863 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 04:43:38,056 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 04:43:44,774 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.15s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-04 04:43:44,774 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.15s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-04 04:43:44,779 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 04:43:44,780 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 04:43:54,905 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 04:43:54,906 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 04:46:34,834 - distributed.worker - INFO - Stopping worker at tcp://10.120.104.11:46393. Reason: worker-close
2023-04-04 04:46:34,834 - distributed.worker - INFO - Stopping worker at tcp://10.120.104.11:44455. Reason: worker-handle-scheduler-connection-broken
2023-04-04 04:46:34,835 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.104.11:36467'. Reason: nanny-close
2023-04-04 04:46:34,835 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-04-04 04:46:34,836 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.104.11:44293'. Reason: nanny-close
2023-04-04 04:46:34,835 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.120.104.11:52444 remote=tcp://10.120.104.11:8786>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1868, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 269, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-04-04 04:46:34,837 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-04-04 04:46:38,038 - distributed.nanny - WARNING - Worker process still alive after 3.1999951171875 seconds, killing
2023-04-04 04:46:38,039 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-04-04 04:46:38,836 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 607, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 390, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 844, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-04-04 04:46:38,838 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 607, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 390, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 844, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-04-04 04:46:38,839 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1216757 parent=1216736 started daemon>
2023-04-04 04:46:38,839 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1216754 parent=1216736 started daemon>
2023-04-04 04:46:39,313 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1216757 exit status was already read will report exitcode 255
