RUNNING: "python -m dask_cuda.cli.dask_cuda_worker --rmm-pool-size=28G
             --local-directory=/tmp/
             --scheduler-file=/root/cugraph/python/cugraph-pyg/cugraph_pyg/examples/scheduler.json
             --memory-limit=auto
             --device-memory-limit=auto
            "
2023-04-04 04:25:30,249 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.104.11:43567'
2023-04-04 04:25:30,251 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.104.11:34749'
2023-04-04 04:25:31,383 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-worker-space/worker-9w3m820y', purging
2023-04-04 04:25:31,384 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-worker-space/worker-9fhp0ctn', purging
2023-04-04 04:25:31,384 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-04-04 04:25:31,384 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-04-04 04:25:31,399 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-04-04 04:25:31,399 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-04-04 04:25:31,635 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-04-04 04:25:31,661 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-04-04 04:25:32,987 - distributed.worker - INFO -       Start worker at:  tcp://10.120.104.11:34957
2023-04-04 04:25:32,987 - distributed.worker - INFO -          Listening to:  tcp://10.120.104.11:34957
2023-04-04 04:25:32,987 - distributed.worker - INFO -          dashboard at:        10.120.104.11:45631
2023-04-04 04:25:32,987 - distributed.worker - INFO - Waiting to connect to:   tcp://10.120.104.11:8786
2023-04-04 04:25:32,987 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 04:25:32,987 - distributed.worker - INFO -               Threads:                          1
2023-04-04 04:25:32,987 - distributed.worker - INFO -                Memory:                 755.28 GiB
2023-04-04 04:25:32,987 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-ollgo3_j
2023-04-04 04:25:32,988 - distributed.worker - INFO - Starting Worker plugin RMMSetup-2e166a4e-14bb-4dd8-a4c5-d4295e0fa56e
2023-04-04 04:25:33,001 - distributed.worker - INFO -       Start worker at:  tcp://10.120.104.11:45003
2023-04-04 04:25:33,001 - distributed.worker - INFO -          Listening to:  tcp://10.120.104.11:45003
2023-04-04 04:25:33,001 - distributed.worker - INFO -          dashboard at:        10.120.104.11:41085
2023-04-04 04:25:33,001 - distributed.worker - INFO - Waiting to connect to:   tcp://10.120.104.11:8786
2023-04-04 04:25:33,001 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 04:25:33,001 - distributed.worker - INFO -               Threads:                          1
2023-04-04 04:25:33,001 - distributed.worker - INFO -                Memory:                 755.28 GiB
2023-04-04 04:25:33,001 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-xm0vt5t5
2023-04-04 04:25:33,002 - distributed.worker - INFO - Starting Worker plugin PreImport-c44da41b-8a39-4d2f-a658-6f9599c43c4c
2023-04-04 04:25:33,002 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-d283aaa7-768a-4a0c-8020-a192aaac6d47
2023-04-04 04:25:33,002 - distributed.worker - INFO - Starting Worker plugin RMMSetup-87a81dbd-e741-40c4-9156-6e7040533cea
2023-04-04 04:25:33,128 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-7c096146-bc54-4d1b-8a47-be4c6fca9546
2023-04-04 04:25:33,129 - distributed.worker - INFO - Starting Worker plugin PreImport-cc2f3668-01cb-48d8-84c1-6d518e856d34
2023-04-04 04:25:33,129 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 04:25:33,156 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 04:25:33,160 - distributed.worker - INFO -         Registered to:   tcp://10.120.104.11:8786
2023-04-04 04:25:33,160 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 04:25:33,162 - distributed.core - INFO - Starting established connection to tcp://10.120.104.11:8786
2023-04-04 04:25:33,167 - distributed.worker - INFO -         Registered to:   tcp://10.120.104.11:8786
2023-04-04 04:25:33,167 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 04:25:33,169 - distributed.core - INFO - Starting established connection to tcp://10.120.104.11:8786
2023-04-04 04:25:55,927 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 04:25:55,929 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 04:25:56,734 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 04:25:56,734 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 04:25:57,370 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 04:25:57,385 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 04:25:57,392 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 04:25:57,396 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 04:26:05,694 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 04:26:05,892 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 04:26:12,645 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.04s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-04 04:26:12,646 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.04s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-04 04:26:12,653 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 04:26:12,653 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 04:26:22,630 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 04:26:22,631 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 04:33:03,774 - distributed.worker - INFO - Stopping worker at tcp://10.120.104.11:45003. Reason: worker-close
2023-04-04 04:33:03,774 - distributed.worker - INFO - Stopping worker at tcp://10.120.104.11:34957. Reason: worker-close
2023-04-04 04:33:03,774 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.104.11:43567'. Reason: nanny-close
2023-04-04 04:33:03,775 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-04-04 04:33:03,775 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.104.11:34749'. Reason: nanny-close
2023-04-04 04:33:03,776 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-04-04 04:33:03,775 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.120.104.11:33592 remote=tcp://10.120.104.11:8786>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1868, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 269, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-04-04 04:33:03,775 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.120.104.11:33580 remote=tcp://10.120.104.11:8786>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1868, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 269, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-04-04 04:33:06,978 - distributed.nanny - WARNING - Worker process still alive after 3.1999963378906253 seconds, killing
2023-04-04 04:33:06,978 - distributed.nanny - WARNING - Worker process still alive after 3.1999990844726565 seconds, killing
2023-04-04 04:33:07,906 - distributed.nanny - INFO - Worker process 1203262 was killed by signal 9
2023-04-04 04:33:07,913 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 607, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 390, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 844, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-04-04 04:33:07,914 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1203259 parent=1203228 started daemon>
2023-04-04 04:33:08,238 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1203259 exit status was already read will report exitcode 255
