RUNNING: "python -m dask_cuda.cli.dask_cuda_worker --rmm-pool-size=28G
             --local-directory=/tmp/
             --scheduler-file=/root/cugraph/python/cugraph-pyg/cugraph_pyg/examples/scheduler.json
             --memory-limit=auto
             --device-memory-limit=auto
            "
2023-04-04 14:36:00,601 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.104.11:35601'
2023-04-04 14:36:00,603 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.104.11:43539'
2023-04-04 14:36:01,770 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-04-04 14:36:01,770 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-04-04 14:36:01,787 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-04-04 14:36:01,787 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-04-04 14:36:02,020 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-04-04 14:36:02,061 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-04-04 14:36:03,322 - distributed.worker - INFO -       Start worker at:  tcp://10.120.104.11:33723
2023-04-04 14:36:03,322 - distributed.worker - INFO -          Listening to:  tcp://10.120.104.11:33723
2023-04-04 14:36:03,322 - distributed.worker - INFO -          dashboard at:        10.120.104.11:35841
2023-04-04 14:36:03,322 - distributed.worker - INFO - Waiting to connect to:   tcp://10.120.104.11:8786
2023-04-04 14:36:03,322 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 14:36:03,322 - distributed.worker - INFO -               Threads:                          1
2023-04-04 14:36:03,322 - distributed.worker - INFO -                Memory:                 755.28 GiB
2023-04-04 14:36:03,322 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-44e_8q2g
2023-04-04 14:36:03,323 - distributed.worker - INFO - Starting Worker plugin RMMSetup-4ff520a1-bed0-49d3-a61b-1ff13d74833a
2023-04-04 14:36:03,333 - distributed.worker - INFO -       Start worker at:  tcp://10.120.104.11:44377
2023-04-04 14:36:03,333 - distributed.worker - INFO -          Listening to:  tcp://10.120.104.11:44377
2023-04-04 14:36:03,333 - distributed.worker - INFO -          dashboard at:        10.120.104.11:46601
2023-04-04 14:36:03,333 - distributed.worker - INFO - Waiting to connect to:   tcp://10.120.104.11:8786
2023-04-04 14:36:03,334 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 14:36:03,334 - distributed.worker - INFO -               Threads:                          1
2023-04-04 14:36:03,334 - distributed.worker - INFO -                Memory:                 755.28 GiB
2023-04-04 14:36:03,334 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-uunt_ht8
2023-04-04 14:36:03,334 - distributed.worker - INFO - Starting Worker plugin RMMSetup-af7c967e-3084-4a3d-8f76-bd78a9590f81
2023-04-04 14:36:03,462 - distributed.worker - INFO - Starting Worker plugin PreImport-3c42212c-3860-4a5b-baf8-6c7285635273
2023-04-04 14:36:03,462 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-bf839f65-ba78-4dd8-836b-1a3409ed7a74
2023-04-04 14:36:03,463 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 14:36:03,489 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-0276fc3f-8078-4cd0-94be-3cf60423ae17
2023-04-04 14:36:03,490 - distributed.worker - INFO - Starting Worker plugin PreImport-3eb884c1-8a82-432a-bc56-85460355c631
2023-04-04 14:36:03,490 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 14:36:03,493 - distributed.worker - INFO -         Registered to:   tcp://10.120.104.11:8786
2023-04-04 14:36:03,493 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 14:36:03,495 - distributed.core - INFO - Starting established connection to tcp://10.120.104.11:8786
2023-04-04 14:36:03,501 - distributed.worker - INFO -         Registered to:   tcp://10.120.104.11:8786
2023-04-04 14:36:03,502 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 14:36:03,504 - distributed.core - INFO - Starting established connection to tcp://10.120.104.11:8786
2023-04-04 14:36:23,315 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:36:23,315 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:36:24,129 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 14:36:24,129 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 14:36:24,817 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:36:24,824 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:36:24,833 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 14:36:24,838 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 14:36:33,269 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 14:36:33,283 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 14:36:40,181 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.14s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-04 14:36:40,181 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.15s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-04 14:36:40,188 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 14:36:40,188 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 14:36:50,151 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:36:50,152 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:36:50,688 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:36:50,689 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:36:53,987 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:36:53,987 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:36:55,224 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:36:55,224 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:01,281 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:01,281 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:02,526 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:02,526 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:07,348 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:07,348 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:09,581 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:09,582 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:14,325 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:14,325 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:16,382 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:16,383 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:22,447 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:22,447 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:24,619 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:24,619 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:29,990 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:29,993 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:31,211 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:31,212 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:36,038 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:36,039 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:38,234 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:38,234 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:42,142 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:37:42,143 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 14:42:28,269 - distributed.worker - INFO - Stopping worker at tcp://10.120.104.11:33723. Reason: worker-handle-scheduler-connection-broken
2023-04-04 14:42:28,269 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.104.11:35601'. Reason: nanny-close
2023-04-04 14:42:28,269 - distributed.worker - INFO - Stopping worker at tcp://10.120.104.11:44377. Reason: worker-handle-scheduler-connection-broken
2023-04-04 14:42:28,269 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-04-04 14:42:28,270 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.104.11:43539'. Reason: nanny-close
2023-04-04 14:42:28,271 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-04-04 14:42:28,286 - distributed.worker - ERROR - Timed out during handshake while connecting to tcp://10.120.104.11:43539 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1868, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 869, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1138, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 329, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.120.104.11:51192 remote=tcp://10.120.104.11:43539>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 752, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1573, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1262, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1506, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1427, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 334, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.120.104.11:43539 after 100 s
2023-04-04 14:42:31,472 - distributed.nanny - WARNING - Worker process still alive after 3.1999963378906253 seconds, killing
2023-04-04 14:42:31,472 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-04-04 14:42:32,270 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 607, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 390, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 844, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-04-04 14:42:32,272 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 607, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 390, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 844, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-04-04 14:42:32,273 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1317009 parent=1316976 started daemon>
2023-04-04 14:42:32,273 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1317006 parent=1316976 started daemon>
2023-04-04 14:42:32,876 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1317006 exit status was already read will report exitcode 255
