RUNNING: "python -m dask_cuda.cli.dask_cuda_worker --rmm-pool-size=28G
             --local-directory=/tmp/
             --scheduler-file=/root/cugraph/python/cugraph-pyg/cugraph_pyg/examples/scheduler.json
             --memory-limit=auto
             --device-memory-limit=auto
            "
2023-04-04 18:12:45,654 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.104.11:39559'
2023-04-04 18:12:45,658 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.104.11:35035'
2023-04-04 18:12:46,798 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-04-04 18:12:46,798 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-04-04 18:12:46,808 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-04-04 18:12:46,808 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-04-04 18:12:47,052 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-04-04 18:12:47,071 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-04-04 18:12:48,435 - distributed.worker - INFO -       Start worker at:  tcp://10.120.104.11:43147
2023-04-04 18:12:48,436 - distributed.worker - INFO -          Listening to:  tcp://10.120.104.11:43147
2023-04-04 18:12:48,436 - distributed.worker - INFO -          dashboard at:        10.120.104.11:46483
2023-04-04 18:12:48,436 - distributed.worker - INFO - Waiting to connect to:   tcp://10.120.104.11:8786
2023-04-04 18:12:48,436 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 18:12:48,436 - distributed.worker - INFO -               Threads:                          1
2023-04-04 18:12:48,436 - distributed.worker - INFO -                Memory:                 755.28 GiB
2023-04-04 18:12:48,436 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-s1h2ey6o
2023-04-04 18:12:48,436 - distributed.worker - INFO - Starting Worker plugin RMMSetup-1aee7d29-a2f7-4eb0-a499-a6dab47a11d7
2023-04-04 18:12:48,450 - distributed.worker - INFO -       Start worker at:  tcp://10.120.104.11:33345
2023-04-04 18:12:48,450 - distributed.worker - INFO -          Listening to:  tcp://10.120.104.11:33345
2023-04-04 18:12:48,450 - distributed.worker - INFO -          dashboard at:        10.120.104.11:35103
2023-04-04 18:12:48,450 - distributed.worker - INFO - Waiting to connect to:   tcp://10.120.104.11:8786
2023-04-04 18:12:48,451 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 18:12:48,451 - distributed.worker - INFO -               Threads:                          1
2023-04-04 18:12:48,451 - distributed.worker - INFO -                Memory:                 755.28 GiB
2023-04-04 18:12:48,451 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-a7x0sqgf
2023-04-04 18:12:48,451 - distributed.worker - INFO - Starting Worker plugin RMMSetup-a9742fa0-5a73-4aa0-acc6-e7594e092879
2023-04-04 18:12:48,597 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-06cb81c9-5afa-4a9d-bc8c-fe81908a1d57
2023-04-04 18:12:48,597 - distributed.worker - INFO - Starting Worker plugin PreImport-a96eae8e-b578-4682-827e-6c69788aa2b4
2023-04-04 18:12:48,598 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-e02453ec-50e0-49e7-9743-82abf2eeb08c
2023-04-04 18:12:48,598 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 18:12:48,599 - distributed.worker - INFO - Starting Worker plugin PreImport-c4f63e69-333b-4575-a9b4-b79ae4afeb01
2023-04-04 18:12:48,600 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 18:12:48,609 - distributed.worker - INFO -         Registered to:   tcp://10.120.104.11:8786
2023-04-04 18:12:48,609 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 18:12:48,610 - distributed.worker - INFO -         Registered to:   tcp://10.120.104.11:8786
2023-04-04 18:12:48,610 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 18:12:48,611 - distributed.core - INFO - Starting established connection to tcp://10.120.104.11:8786
2023-04-04 18:12:48,612 - distributed.core - INFO - Starting established connection to tcp://10.120.104.11:8786
2023-04-04 18:13:11,379 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:11,381 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:12,176 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 18:13:12,176 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 18:13:12,811 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:12,831 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:12,837 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 18:13:12,838 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 18:13:21,115 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 18:13:21,135 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 18:13:27,855 - distributed.core - INFO - Event loop was unresponsive in Worker for 14.83s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-04 18:13:27,855 - distributed.core - INFO - Event loop was unresponsive in Worker for 14.83s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-04 18:13:27,862 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 18:13:27,862 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 18:13:37,884 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:37,886 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:38,352 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:38,352 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:40,603 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:40,604 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:42,630 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:42,631 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:42,858 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:42,858 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:46,103 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:46,105 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:46,824 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:46,824 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:50,820 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:50,820 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:51,036 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:51,037 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:54,524 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:54,524 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:54,733 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:54,733 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:58,238 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:58,239 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:58,439 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:13:58,440 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:14:01,924 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:14:01,925 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:14:01,981 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:14:01,981 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:14:04,812 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:14:04,812 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:14:06,823 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:14:06,825 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 18:16:32,430 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.104.11:39559'. Reason: nanny-close
2023-04-04 18:16:32,430 - distributed.worker - INFO - Stopping worker at tcp://10.120.104.11:43147. Reason: worker-handle-scheduler-connection-broken
2023-04-04 18:16:32,430 - distributed.worker - INFO - Stopping worker at tcp://10.120.104.11:33345. Reason: worker-handle-scheduler-connection-broken
2023-04-04 18:16:32,431 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-04-04 18:16:32,432 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.104.11:35035'. Reason: nanny-close
2023-04-04 18:16:32,432 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-04-04 18:16:32,459 - distributed.worker - ERROR - Timed out during handshake while connecting to tcp://10.120.104.11:35035 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1868, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 869, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1138, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 329, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.120.104.11:57164 remote=tcp://10.120.104.11:35035>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 752, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1573, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1262, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1506, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1427, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 334, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.120.104.11:35035 after 100 s
2023-04-04 18:16:35,636 - distributed.nanny - WARNING - Worker process still alive after 3.1999963378906253 seconds, killing
2023-04-04 18:16:35,639 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-04-04 18:16:36,432 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 607, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 390, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 844, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-04-04 18:16:36,434 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 607, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 390, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 844, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-04-04 18:16:36,434 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1487418 parent=1487394 started daemon>
2023-04-04 18:16:36,435 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1487415 parent=1487394 started daemon>
2023-04-04 18:16:37,048 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1487415 exit status was already read will report exitcode 255
